// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ConsultaLivroTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void consultaLivro() {
    driver.get("https://www.alibris.com/");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.id("searchBox")).click();
    driver.findElement(By.id("searchBox")).sendKeys("The art of Software testing");
    driver.findElement(By.id("searchBox")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("li:nth-child(1) > .left:nth-child(1) .button:nth-child(1) > span:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".product-container:nth-child(2) .price > p")).getText(), is("$1.45 $160.00"));
  }
}
